### ISSUE TITLE
iOS Support

### ISSUE THREAD

**Issue by bloechl** [tomcx/tame4#1]
Hello!
for me it seems that on iOS devices the onready function isn't called. Could you please habe a look on it.

**Comment by tomcx** [comment]
I don't use iOS but I'll try to get a device from a friend. Does this issue show up with mobile safari? Have you tried another browser?

**Comment by bloechl** [comment]
Yes I've also tried Chrome on iOS. Thank you for your great work.

**Comment by tomcx** [comment]
Ok, yesterday I tested the visualization of my home with an iPad (Mobile Safari). No problems so far. We need more information. First you should activate the Debug Console as described  [here](http://browsers.about.com/od/allaboutwebbrowsers/ss/iphonedebugger.htm). Then open your website and have a look at the console. There should be messages like this:

`TAME library version: V4.0 160317`
`TAME library warning: AMS port number is not set! Default port 801 will be used.`
`TAME library info: Target information: NetId: 100.4.5.9.3., AMS port: 801 , alignment: 4`
`TAME library info: Start fetching the symbols from PLC.`
`POST http://192.168.123.123/TcAdsWebService/TcAdsWebService.dll  200 OK  486ms`
`POST http://192.168.123.123/TcAdsWebService/TcAdsWebService.dll 200 OK 221ms`
`TAME library info: End of fetching the symbols.`
`TAME library info: Symbol table ready.`
`TAME library info: Calling the "onReady" function.`
`POST http://192.168.123.123/TcAdsWebService/TcAdsWebService.dll  200 OK 23ms`
`POST http://192.168.123.123/TcAdsWebService/TcAdsWebService.dll  200 OK 89ms`
`POST http://192.168.123.123/TcAdsWebService/TcAdsWebService.dll  200 OK 37ms`

If something is wrong there also should be some error messages. Can you send me the output of the console?

**Comment by bloechl** [comment]
OK, I will try to get an Output of the console but actually it isn't possible to debug without without a Mac. Eventually it's a Problem, that I use the tpy-file and ntlm authentification?

**Comment by bloechl** [comment]
OK I,ve found the problem: "Can't parse the symbol file cause your brower (browser?) does not provide a DOMParser function". PS: I was looking a long time for a possibility to debug on iOS-devices and found this one: [https://blog.idrsolutions.com/2015/02/remote-debugging-ios-safari-on-os-x-windows-and-linux/](url)

**Comment by tomcx** [comment]
You should be able to run the debug console on the device. The link I've posted above shows you how. Which OS version do you have? I've read that the DOMparser isn't available on iOS 7 but should work on iOS 8+. 
On [http://www.w3schools.com/xml/dom_intro.asp](http://www.w3schools.com/xml/dom_intro.asp) there are 2 examples: "Loading an XML File" and "Loading an XML String". Can you try both and write back if they work?

**Comment by bloechl** [comment]
I use iOS 9.3.1 but there aren't developer settings anymore. The two examples work for me.

**Comment by tomcx** [comment]
That's strange cause I use the same function as in the "Loading an XML String" example. I think the problem is the check for the DOMParser. Maybe iOS has different return value. Can you test the new version: [https://github.com/tomcx/tame4/tree/parser_issue](https://github.com/tomcx/tame4/tree/parser_issue)

**Comment by tomcx** [comment]
Successfully tested by a user. Issue closed.
