### ISSUE TITLE
Chrome Warning

### ISSUE THREAD

**Issue by bloechl** [tomcx/tame4#10]
Hello!

Chrome is giving me following warning:

Subresource requests whose URLs contain embedded credentials (e.g. `https://user:pass@host/`) are deprecated, and will be blocked in M59, around June 2017. See https://www.chromestatus.com/feature/5669008342777856 for more details.
J @ tame.js:11
TAME.WebServiceClient @ tame.js:11
TAME.WebServiceClient.createClient @ tame.js:11

What to do?

**Comment by tomcx** [comment]
I don't get such a message (Chrome 57 on Debian).
