### ISSUE TITLE
Using handles

### ISSUE THREAD

**Issue by sagishoffer** [tomcx/tame4#11]
Hi,

First of all thanks for a great library!
I wanted to ask about how to use handles. I have structs inside structs and also struct that contain array of structs. I've used the manual but could not get it right. Can you provide a little example please? 

Thanks and keep up the good job!

**Comment by tomcx** [comment]
Can you post some more information? What exactly do you want to read? Whole structures or elements of them? How deeply are they nested? The combination of TPY file + handles covers some cases but there are limitations.

**Comment by sagishoffer** [comment]
Hi,

Thanks for your reply. I think I have resolved my problem.
I'll keep you posted!
