### ISSUE TITLE
TAME with angular2

### ISSUE THREAD

**Issue by sagishoffer** [tomcx/tame4#12]
Hello,

Thanks for a great library!
My previous project built with Jquery. Today I have migrate the project to angular2 framework.
There is a problem trying to read arrays or structs. I have followed your documentation but couldn't resolve the issue. Any idea what can be the problem?

**Comment by tomcx** [comment]
I don't know angular2. Can you provide more information? What exactly does not work?

**Comment by sagishoffer** [comment]
Apparently it was an angular scope issue, now it works fine. 
I have other problem now. When i'm trying to read an array of byte with 6 elements by using Plc.readArrayOfByte it works good but when i'm trying to read the same array inside Plc.sumReadReq it gives me only the first 2 elements. Any idea why?

**Comment by tomcx** [comment]
Not really. Do you use the TPY file?

**Comment by sagishoffer** [comment]
Actually i'm not sure what is TPY file, i'm using getHandles() method.

**Comment by tomcx** [comment]
I can't reproduce this behavior. Using handles I can read an array of bytes with a SumReadReq without any problems. Can you send me the code? Are there error messages?

**Comment by sagishoffer** [comment]
I have problems also with SumReadReq primitive types. I cant point exactly the problem but it wont work without declaring the type of each variable. Maybe its related to TypeScript that I use in the angular project. Thanks anyway!
