### ISSUE TITLE
Some crippling syntax error in WinCE IE, fix inc.

### ISSUE THREAD

**Issue by Jouzer** [tomcx/tame4#14]
Hey! This package is a gift from heavens for my new project, I was set out to do something similar by myself, but now that I see how much stuff is involved with this I'm very glad I didn't have to do that part of the project.

With the initial tests, I noticed that when I try to connect with WinCE own version of Internet Explorer, it crashes with errors. I was able to find and fix the said errors and I'm glad to find out it works (more or less) in the CE Internet Explorer too. This is important for me because I use the Beckhoff Control Panel CP6606 in my project and I would like to access the site locally too.

I'm new to GitHub and web development in general so I'm not sure about branching nor how to package the .tame.js as you've done but I was able to debug and correct by replaceing that tame.js with tame-with-comments.js.

The 'error' was that the IE of WinCE can't handle var { } where the last entry was commented out, resulting in "," being the last character of the code inside brackets. There was I think 3 iterations of those and 1 which had "," without any commented section afterwards . 

Thanks a bunch for letting us use this!

**Comment by tomcx** [comment]
I don't know how I could help you, cause it's seems to be a browser specific issue and I have no environment to debug this. You could try a better browser for CE: [Zetakey](https://www.zetakey.com)

**Comment by Jouzer** [comment]
Oh I guess I worded my post wrong. What I'm trying to say is I found the fix and wanted to let you (or anyone with the same issue) know / contribute, it works just fine in WinCE IE now that I fixed those few parts in the code. 

Yeah Zetakey is good, I'll probably end up using that soon.

**Comment by tomcx** [comment]
Just post the code and I'll have look at it.

**Comment by Jouzer** [comment]
Here, sorry I tried to branch but I figured it's probably only for select group of people, so I just attached it here

This is the fixed version, there should be about 3 alterations to the code, 2 of which can be found by searching "//,"

[tame-w-comments.txt](https://github.com/tomcx/tame4/files/1404432/tame-w-comments.txt)

**Comment by tomcx** [comment]
Ok, I've deleted the commas and uploaded a new version. Should be fine now. Thanks for reporting!
