### ISSUE TITLE
How change amsPort?

### ISSUE THREAD

**Issue by danihbelan** [tomcx/tame4#15]
In your library the amsPort has to be in the range (801-891) but mi IIS assign me the port 35347. So when I try to run the example I have the next error: "TAME library error: AMS Port Number (35347) is out of range (801-891)!" @tomcx

**Comment by tomcx** [comment]
I think you mess something up. The IIS can't assign an AMS port cause it's a TwinCAT internal protocol. The AMS port is the port of your runtime.

[https://infosys.beckhoff.com/english.php?content=../content/1033/tcadscommon/html/tcadscommon_identadsdevice.htm&id=]()

[https://infosys.beckhoff.com/english.php?content=../content/1033/tcsystemmanager/basics/tcsysmgr_configplc_intro.htm&id=](url)

**Comment by danihbelan** [comment]
Thanks for your answer. I had some wrong concepts.
And thanks for your great work with this library, I am working on a project with PLCs and it is very helpful.
Now it is running without problem!!
