### ISSUE TITLE
Error: Cross origin null forbidden

### ISSUE THREAD

**Issue by danihbelan** [tomcx/tame4#17]
When I use the library with express I have this error:
Error: Cross origin null forbidden

How can it be solved? I try with this npm package https://www.npmjs.com/package/cors but don't work.

Thanks @tomcx

**Comment by tomcx** [comment]
I don't know your configuration but it's a security mechanism and the correct way is to set the Access-Control-Allow-Origin header appropriate.

[https://enable-cors.org](url)

**Comment by danihbelan** [comment]
I have TwinCAT in a windows 10 with IIS server. 
When I use the examples, I use the extension for chrome: [CORS](https://chrome.google.com/webstore/detail/allow-control-allow-origi/nlfbmbojpeacfghkpbjhddihlkkiljbi) and works
But with node I don't know how to fix this.
