### ISSUE TITLE
Usage of tame4 in nodejs

### ISSUE THREAD

**Issue by ghost** [tomcx/tame4#19]
Hi tomcx! First of all, you made a great job!! I think Tame4 is really useful and makes things much more easy with respect to the JS WebService offered by Twincat.

I have a question for you, if you can help.

Would you suggest a way to use your library in a NodeJS application? When it comes to function calls made directly from the browser there is no problem, but I would like to create a server that offers a REST API in NodeJS, so that at each request against the REST endpoint the server can call a Tame4 function to retrieve data from Twincat.

The problem is that, as I have seen, Tame4 is "browser" based: it relies in XmlHttpRequests and "window" calls, for instance, and I cannot use them in a "nodejs" environment..

Hope you understood my doubts and maybe can give me some hints :)

Nicola

**Comment by tomcx** [comment]
Hi, as you already found out TAME works only in browser based environments (window, XHTTP). The only hint I can give you is to have look at the Beckhoff Information System. They also provide a ADS Javascript Library. Maybe you'll find a way but I guess you have to do it from scratch. 

https://infosys.beckhoff.com/content/1033/tcadswebservice/html/note.htm?id=2409514555020299687
