### ISSUE TITLE
Direct link to command

### ISSUE THREAD

**Issue by RikMe** [tomcx/tame4#20]
Hi Tom, is there a way to invoke commands trough a specific URL. I'm experimenting with linking Tame to Siri shortcuts, my way of doing so would be to invoke commands directly trough the URL.

**Comment by tomcx** [comment]
I don't know how to do this directly. Maybe you could build webpages and invoke the commands you need by "onLoad". You can also have look at the ADS-Script-DLL. I used it before creating TAME and I think it suits better your needs.

[ https://infosys.beckhoff.com/english.php?content=../content/1033/tcsample_webservice/html/webservice_sample_intro.htm&id=](url)
