### ISSUE TITLE
No values from TwinCat 3.1

### ISSUE THREAD

**Issue by 123Gonzo7** [tomcx/tame4#3]
Hello,
first many thanks for your great work!

I try with Tame 4.0.1 to connect a variable from TwinCat 3.1 (CX9020) and show
the values in an apache cordova android app. (With TwinCat 2.11 it works)
The connection works. Unfortunately i get no value from plc (MAIN.Ramp1).
Code:
`  
(webservice.js)  
var Plc;

function startClient(handles) {

```
Plc =  TAME.WebServiceClient.createClient({
    serviceUrl: 'http://192.168.1.88/TcAdsWebService/TcAdsWebService.dll',
    amsNetId: '192.168.1.88.1.1',
    amsPort:   '851',      
    alignment: '8',      
    language: 'en',    
    onReady: dataconnection   
});
```

}

(demo.js)
  Plc.sumReadReq({
            id: 1,  
            items: [
                {
                    name: 'MAIN.Ramp1',
                    jvar: 'ai_flow.data'
                }
            ],
            oc: function() {

```
        }
    });
```

`

Still needs anything set in the webservice.js like typ paht?
Thanks, regards
Daniel

**Comment by 123Gonzo7** [comment]
Sorry. was an internal script error. 
It run! 
Thanks for your work! It is very useful for homeautomation

**Comment by tomcx** [comment]
That's what it's intended for. Glad to hear that it works.

**Comment by shivmanagond** [comment]
Hi
Whtas is TAME?How can i use with beckhoff PLC with Nodered ?

**Comment by tomcx** [comment]
TAME does not work with Node-RED. It is intended for websites or webapps in browser based environments. I made the NPM module for an easier integration in Ionic or Angular projects.
