### ISSUE TITLE
Error when connection lost

### ISSUE THREAD

**Issue by 123Gonzo7** [tomcx/tame4#4]
Hello,
is there a way to get an error when connection to plc is lost or a Reconnect function or any idea to solve it?
Many thanks
Daniel

**Comment by tomcx** [comment]
I don't know exactly what you mean. There isn't a permanent connection or so. Just single requests.

**Comment by tomcx** [comment]
Would it help to have an "on error" function similar to the "on complete" function? The function would be execute every time a request fails.

**Comment by 123Gonzo7** [comment]
Hi,
Thank you for your feedback
I have solved the problem with Try Catch and Watchdog func.. I think it is not
R´required to add an "on error" function.
But thank you very much!

**Comment by tomcx** [comment]
There is a new on-error function in V4.1 Should help to solve such problems.
