### ISSUE TITLE
TPY-parser

### ISSUE THREAD

**Issue by bloechl** [tomcx/tame4#5]
Hello!

I have a Problem with the tpy-Parser, when I include the M-Bus lib.
I've figured out that the problem must be at this datatype (at subitem pcomin)

<DataType>
			<Name Decoration="1018637D" IsDefinedInLibrary="1" Library="TcMBus.lib">FB_KL6781WriteRegisters</Name>
			<BitSize>528</BitSize>
			<SubItem>
				<Name Constant="1" IsDefinedInLibrary="1" Library="TcMBus.lib">TIME_OUT_VALUE</Name>
				<Type>TIME</Type>
				<BitSize>32</BitSize>
				<BitOffs>0</BitOffs>
			</SubItem>
			<SubItem>
				<Name Constant="1" IsDefinedInLibrary="1" Library="TcMBus.lib">REGISTERNUMBERMASK</Name>
				<Type>BYTE</Type>
				<BitSize>8</BitSize>
				<BitOffs>32</BitOffs>
			</SubItem>
			<SubItem>
				<Name Constant="1" IsDefinedInLibrary="1" Library="TcMBus.lib">REGISTERWRITEMASK</Name>
				<Type>BYTE</Type>
				<BitSize>8</BitSize>
				<BitOffs>40</BitOffs>
			</SubItem>
			<SubItem>
				<Name IsDefinedInLibrary="1" Library="TcMBus.lib">state</Name>
				<Type>INT</Type>
				<BitSize>16</BitSize>
				<BitOffs>48</BitOffs>
			</SubItem>
			<SubItem>
				<Name IsDefinedInLibrary="1" Library="TcMBus.lib">TriggerExecute</Name>
				<Type Decoration="1003051C">R_TRIG</Type>
				<BitSize>24</BitSize>
				<BitOffs>64</BitOffs>
			</SubItem>
			<SubItem>
				<Name IsDefinedInLibrary="1" Library="TcMBus.lib">NumRegisters</Name>
				<Type>UINT</Type>
				<BitSize>16</BitSize>
				<BitOffs>88</BitOffs>
			</SubItem>
			<SubItem>
				<Name IsDefinedInLibrary="1" Library="TcMBus.lib">n</Name>
				<Type>UINT</Type>
				<BitSize>16</BitSize>
				<BitOffs>104</BitOffs>
			</SubItem>
			<SubItem>
				<Name IsDefinedInLibrary="1" Library="TcMBus.lib">Register</Name>
				<Type>BYTE</Type>
				<BitSize>8</BitSize>
				<BitOffs>120</BitOffs>
			</SubItem>
			<SubItem>
				<Name IsDefinedInLibrary="1" Library="TcMBus.lib">Value</Name>
				<Type>WORD</Type>
				<BitSize>16</BitSize>
				<BitOffs>128</BitOffs>
			</SubItem>
			<SubItem>
				<Name IsDefinedInLibrary="1" Library="TcMBus.lib">Timeout</Name>
				<Type Decoration="10060D24">TON</Type>
				<BitSize>120</BitSize>
				<BitOffs>144</BitOffs>
			</SubItem>
			<SubItem>
				<Name IsDefinedInLibrary="1" Library="TcMBus.lib">pCTRL</Name>
				<Type Pointer="1">BYTE</Type>
				<BitSize>32</BitSize>
				<BitOffs>264</BitOffs>
			</SubItem>
			<SubItem>
				<Name IsDefinedInLibrary="1" Library="TcMBus.lib">pSTATUS</Name>
				<Type Pointer="1">BYTE</Type>
				<BitSize>32</BitSize>
				<BitOffs>296</BitOffs>
			</SubItem>
			<SubItem>
				<Name IsDefinedInLibrary="1" Library="TcMBus.lib">SaveCTRL</Name>
				<Type>BYTE</Type>
				<BitSize>8</BitSize>
				<BitOffs>328</BitOffs>
			</SubItem>
			<SubItem>
				<Name FbParameter="Input" IsDefinedInLibrary="1" Library="TcMBus.lib">Execute</Name>
				<Type>BOOL</Type>
				<BitSize>8</BitSize>
				<BitOffs>336</BitOffs>
			</SubItem>
			<SubItem>
				<Name FbParameter="Input" IsDefinedInLibrary="1" Library="TcMBus.lib">Mode</Name>
				<Type Decoration="300006FD">E_KL6781ComSerialLineMode</Type>
				<BitSize>16</BitSize>
				<BitOffs>344</BitOffs>
			</SubItem>
			<SubItem>
				<Name FbParameter="Input" IsDefinedInLibrary="1" Library="TcMBus.lib">pComIn</Name>
				<Type Decoration="20010186" Pointer="1">ARRAY [0..65] OF BYTE</Type>
				<Comment>
					<![CDATA[for universal register communication]]>
				</Comment>
				<BitSize>32</BitSize>
				<BitOffs>360</BitOffs>
			</SubItem>
			<SubItem>
				<Name FbParameter="Input" IsDefinedInLibrary="1" Library="TcMBus.lib">pComOut</Name>
				<Type Decoration="20010186" Pointer="1">ARRAY [0..65] OF BYTE</Type>
				<Comment>
					<![CDATA[for universal register communication]]>
				</Comment>
				<BitSize>32</BitSize>
				<BitOffs>392</BitOffs>
			</SubItem>
			<SubItem>
				<Name FbParameter="Input" IsDefinedInLibrary="1" Library="TcMBus.lib">SizeComIn</Name>
				<Type>UINT</Type>
				<BitSize>16</BitSize>
				<BitOffs>424</BitOffs>
			</SubItem>
			<SubItem>
				<Name FbParameter="Input" IsDefinedInLibrary="1" Library="TcMBus.lib">pRegisterList</Name>
				<Type Decoration="20011D88" Pointer="1">ARRAY [0..63] OF ST_KL6781ComRegisterData</Type>
				<BitSize>32</BitSize>
				<BitOffs>440</BitOffs>
			</SubItem>
			<SubItem>
				<Name FbParameter="Input" IsDefinedInLibrary="1" Library="TcMBus.lib">SizeRegisterList</Name>
				<Type>UINT</Type>
				<BitSize>16</BitSize>
				<BitOffs>472</BitOffs>
			</SubItem>
			<SubItem>
				<Name FbParameter="Output" IsDefinedInLibrary="1" Library="TcMBus.lib">Done</Name>
				<Type>BOOL</Type>
				<BitSize>8</BitSize>
				<BitOffs>488</BitOffs>
			</SubItem>
			<SubItem>
				<Name FbParameter="Output" IsDefinedInLibrary="1" Library="TcMBus.lib">Busy</Name>
				<Type>BOOL</Type>
				<BitSize>8</BitSize>
				<BitOffs>496</BitOffs>
			</SubItem>
			<SubItem>
				<Name FbParameter="Output" IsDefinedInLibrary="1" Library="TcMBus.lib">Error</Name>
				<Type>BOOL</Type>
				<BitSize>8</BitSize>
				<BitOffs>504</BitOffs>
			</SubItem>
			<SubItem>
				<Name FbParameter="Output" IsDefinedInLibrary="1" Library="TcMBus.lib">ErrorId</Name>
				<Type Decoration="3000047A">E_KL6781ComError</Type>
				<BitSize>16</BitSize>
				<BitOffs>512</BitOffs>
			</SubItem>
			<FbInfo>
				<CodeIndex>316</CodeIndex>
				<InitIndex>317</InitIndex>
			</FbInfo>
		</DataType>

Please have a look at it.

**Comment by tomcx** [comment]
Can you send the console output with the error message?

**Comment by bloechl** [comment]
![tpy](https://cloud.githubusercontent.com/assets/17129245/20032607/027e9a98-a38e-11e6-9ed0-7f69d33a9ae5.JPG)

**Comment by tomcx** [comment]
It seems like the type definition of the array is missing, but I need the complete TPY to check this. Can you send me the file to t.schmidt.p1 at freenet.de?

**Comment by tomcx** [comment]
The problem is that some data types are missed in the TPY file. Thats why creating the data type table fails. I've changed the code so that the parser runs without the missing objects. The drawback is that there will be wrong data if one tries to access symbols with these data types included. I've added error messages to identify these data types. Please test the new tame.js in the "parser_issue" branch.

**Comment by bloechl** [comment]
OK, I'll check this in the weekend

**Comment by bloechl** [comment]
OK, it works
