### ISSUE TITLE
npm package for smarter installation and updates

### ISSUE THREAD

**Issue by t3easy** [tomcx/tame4#6]
A package.json for NPM would lead to a smarter installation and update procedure.

**Comment by tomcx** [comment]
Ok, it took a while but I'm now at a point to say "YES. But this stuff is new to me and I could need a little help. I've signed in to NPM and Travis. I'v also built a package.json. And as far as I know I have to add a "module.exports" line in the code. But I don't know if it's a good idea to do this in this repo or if it's better to clone it for creating a module. What do you suggest?

**Comment by tomcx** [comment]
Ok, the module is online with v4.3.0. I've imported it in an Ionic project and it seems to work.
